name: simple_get_server
description: Simple standalone server for serving flutter web apps, utilizing get_server, goal is full stack dart.

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  get_server: ^1.1.0