name: simple_shelf_server
description: Simple standalone server for serving flutter web apps, utilizing shelf, goal is full stack dart.

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  functions_framework: ^0.4.0
  shelf: ^1.1.0
  shelf_static: ^1.0.0
  universal_html: ^2.0.8

dev_dependencies:
  build_runner: ^1.12.2
  build_verify: ^2.0.0
  functions_framework_builder: ^0.4.0