name: architecture_setup
description: Collection of widgets, tools, and other useful pieces when beginning a new project
version: 0.0.1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_sheet_localization: ^5.1.0
  freezed_annotation: ^0.14.2
  get: ^4.1.4
  get_storage: ^2.0.2
  remote_state: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.3
  freezed: ^0.14.2
  lint: ^1.5.3
  test: ^1.17.4


flutter:
  uses-material-design: true
